logging:
  level:
    travel.w2m.sh.maint: TRACE
    org.springframework: INFO
    org.apache.catalina.webresources.Cache: ERROR

spring:
  application:
    name: proyecto
  jmx:
    enabled: true
  data:
    jpa.repositories.enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    password: cWyVQXdt0lSn0iEOFjvt
    username: postgres
    hikari:
      maximum-pool-size: 50
      minimum-idle: 2
      idle-timeout: 60000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

server:
  port: 8080